# Generated by Django 5.1 on 2024-08-08 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeinstitution',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 15, 24, 27, 921146, tzinfo=datetime.timezone.utc)),
        ),
    ]
