# Generated by Django 5.1 on 2024-08-08 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_api', '0002_alter_typeinstitution_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeinstitution',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 15, 26, 37, 7010, tzinfo=datetime.timezone.utc)),
        ),
    ]
