# Generated by Django 5.1 on 2024-08-08 15:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution_api', '0002_alter_typeinstitution_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(default='NA', max_length=500)),
                ('state', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2024, 8, 8, 15, 24, 27, 922511, tzinfo=datetime.timezone.utc))),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution_api.institution')),
            ],
            options={
                'db_table': 'tb_agreement',
                'ordering': ['-created_date'],
            },
        ),
    ]
