# Generated by Django 5.1 on 2024-08-08 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agreement_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 15, 25, 54, 35249, tzinfo=datetime.timezone.utc)),
        ),
    ]
