# Generated by Django 5.1 on 2024-08-08 15:25

import agreement_project_api.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreement_api', '0002_alter_agreement_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_project', models.CharField(max_length=500)),
                ('state_project', models.IntegerField(default=agreement_project_api.models.StateProjectEnum['Pending'])),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=datetime.datetime(2024, 8, 8, 15, 25, 54, 35932, tzinfo=datetime.timezone.utc))),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agreement_api.agreement')),
            ],
            options={
                'db_table': 'tb_agreement_project',
                'ordering': ['-created_date'],
            },
        ),
    ]
